# Generated by Django 4.0.4 on 2022-06-27 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addproject', '0010_form_alter_addproject_group_alter_addproject_lang_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproject',
            name='group',
            field=models.CharField(choices=[('production', 'production'), ('commerce', 'commerce'), ('it', 'it'), ('placeofbirth', 'placeofbirth'), ('energy', 'energy')], max_length=20),
        ),
        migrations.AlterField(
            model_name='addproject',
            name='region',
            field=models.CharField(choices=[('Naryn', 'Naryn'), ('Jalal-abad', 'Jalal-abad'), ('Issyk-kul', 'Issyk-kul'), ('Chuy', 'Chuy'), ('Talas', 'Talas'), ('Batken', 'Batken'), ('Osh', 'Osh')], max_length=20),
        ),
    ]
